config/routes.rb
Paintbox::Application.routes.draw do

  resources :sessions, :only => [:new, :create, :destroy]

  resources :swatches

  resources :users do 
    resources :swatches
  end

  # match ':username', :to => 'users#show'
  match 'signup',   :to => 'users#new',         :as => :signup
  match 'login',    :to => 'sessions#new',      :as => :login
  match 'logout',   :to => 'sessions#destroy',  :as => :logout
  match 'settings', :to => 'users#edit',        :as => :settings

  root :to => "swatches#index"

end

app/models/color.rb
class Color < ActiveRecord::Base

  # has_many :swatches

  # validates_presence_of :value
  # validates_length_of :value, :within => 4..7
  # validates_uniqueness_of :value, :case_sensitive => false
  # validates_format_of :value, :with => /^#?([a-f]|[A-F]|[0-9]){3}(([a-f]|[A-F]|[0-9]){3})?$/

end

app/models/swatch.rb
class Swatch < ActiveRecord::Base

  include Rails.application.routes.url_helpers

  belongs_to :user
  belongs_to :color

  default_scope order('created_at desc')
  scope :recent, limit(500)

  validates_presence_of :user_id, :color_id
  default_scope :order => :position
  accepts_nested_attributes_for :color
  validates_associated :color

  def as_json(options = {})
    json = { 
      :color => color.value,
      :user => user.username,
      :url => user_path(user.username)
    }
  end

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base

  has_many :swatches, :dependent => :destroy
  has_many :colors,   :through => :swatches

  attr_accessor   :password
  attr_accessible :username, :email, :password, :password_confirmation

  # scope :public, select('username')

  validates_presence_of     :username
  validates_length_of       :username, :maximum => 50
  validates_format_of       :username, :with => /\A[a-z]+\z/
  validates_uniqueness_of   :username, :case_sensitive => true  
  validates_presence_of     :email
  validates_format_of       :email, :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates_uniqueness_of   :email, :case_sensitive => true
  validates_presence_of     :password
  validates_length_of       :password, :within => 6..40
  validates_confirmation_of :password
  before_save               :encrypt_password

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def remember_me!
    self.remember_token = encrypt("#{salt}--#{id}--#{Time.now.utc}")
    save_without_validation
  end

private
  
  def encrypt_password
    unless password.nil?
      self.salt = make_salt
      self.encrypted_password = encrypt(password)
    end
  end

  def encrypt(string)
    secure_hash("#{salt}#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  protect_from_forgery

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    user = User.authenticate(params[:session][:email], params[:session][:password])
    if user.nil?
      flash.now[:error] = t(:"flash.sign_in_error")
      render "new"
    else
      sign_in user
      flash[:success] = t(:"flash.sign_in")
      redirect_to user_path(user.username)
    end        
  end
  
  def destroy
    sign_out
    flash[:success] = t(:"flash.sign_out")
    redirect_to root_path
  end

end

app/controllers/swatches_controller.rb
class SwatchesController < ApplicationController

  def index
    @user = User.find_by_username(params[:user_id])
    @swatches = @user.nil? ? Swatch.recent : @user.swatches
    respond_to do |format|
      format.html
      format.json { render json: @swatches.as_json }
    end
  end

  def create
    color = Color.find_or_create_by_value(params[:swatch][:colors][:value])
    @swatch = current_user.swatches.build(:color_id => color.id)
    @swatch.save
    render :json => @swatch
  end

  def update
    swatch = Swatch.find(params[:id])
    swatch.update_attributes! params
    render :json => swatch
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate,  :only => [:edit, :update]
  before_filter :correct_user,  :only => [:edit, :update]
  before_filter :admin_user,    :only => [:destroy]  
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find_by_username(params[:id])
    @swatch = Swatch.new if signed_in?
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = t("flash.welcome")
      redirect_to user_path(@user.username)
    else
      flash[:error] = t("flash.error")
      render "new"
    end
  end
  
  def update
    if @user.update_attributes(params[:user])
      flash[:success] = t("flash.profile_updated")
      redirect_to user_path(@user.username)
    else
      flash[:error] = t("flash.error")
      render "edit"
    end
  end
  
  def destroy    
    User.find_by_username(params[:id]).destroy        
    flash[:success] = t("flash.user_deleted")
    redirect_to users_path
  end
  
private
        
  def correct_user
    @user = current_user || User.find_by_username(params[:id])    
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title(title)
    content_for(:page_title) { "/ #{title}" }
  end

  def page_id(page_id)
    content_for(:page_id) { page_id }
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user      
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def signed_in?
    !current_user.nil?
  end  
  
  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end
    
  def current_user?(user)
    user == current_user    
  end  
  
  def user_from_remember_token    
    User.authenticate_with_salt(*remember_token)
  end
  
  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end
      
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page"
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  
  def authenticate
    deny_access unless signed_in?
  end

  private
  
    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
        
end

app/views/application/_flash.html.erb
<% flash = flash() %>
<% if flash.present? %>
  <% flash.each do |key, value| %>
  <p class="flash <%= key %>"><%= value %></p>
  <% end %>
<% end %>

app/views/application/_nav.html.erb
<% if (current_user && current_user.admin?) %>
<nav class="admin">
  <strong>Admin:</strong> <%= link_to t("users"), users_path, :class => "admin" %>
</nav>
<% end %>

<nav>
  <% if signed_in? %>
  <%= link_to t("me"), user_path(current_user.username) %> /
  <%= link_to t("settings"), settings_path %> /        
  <%= link_to t("logout"), logout_path, :method => :delete %> /
  <% else %>
  <%= link_to t("login"), login_path %> / 
  <%= link_to t("signup"), signup_path %> /
  <% end %>
  <%= link_to t("about"), 'https://github.com/meleyal/paintbox#readme' %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">  
  <%= csrf_meta_tag %>  
  <title>paintbox <%= yield :page_title %></title>
  <%= stylesheet_link_tag "application" %>
</head>

<body id="<%= yield :page_id %>" data-id="<%= params[:id] %>">
  <div id="wrap">
    <header>
      <h1><%= link_to("paintbox", root_path) %> <%= yield :page_title %></h1>
      <%= render "flash" %>
      <%= render "nav" %>
    </header>
    <section id="content" class="group">
      <%= yield %>
    </section>
  </div>
  <%= javascript_include_tag "application" %>
  <%= yield :javascripts %>
</body>
</html>

app/views/swatches/_form.html.erb
<div id="picker">

<%= form_for @swatch do |f| %>

  <%= f.fields_for :colors do |c| %>
  <p>
    <%= c.text_field :value, :class => 'color {hash:true}', :size => 7, :maxlength => 7 %><%= f.submit "Add" %>    
  </p>
  <% end %>

<% end %>

</div>

app/views/swatches/_swatch.html.erb
<% link ||= link %>

<li style="background: <%= swatch.color.value %>">
  <% if link %>
    <%= link_to swatch.color.value, user_path(:id => swatch.user.username), :title => swatch.user.username %>        
  <% else %>
    <%= swatch.color.value %>
  <% end %>  
</li>

app/views/swatches/index.html.erb
<ul id="paintbox"></ul>

<% content_for :javascripts do %>
  <%= javascript_include_tag "index" %>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>

  <ol>
    <%= f.input :username %>
    <%= f.input :email %>    
    <%= f.input :password %>    
    <%= f.input :password_confirmation, :label => "Password confirmation", :required => true %>    
    <%= f.button :submit %> 
    <% if @user.new_record? %>
    <span class="or">or <%= link_to t("login"), login_path %></span>
    <% end %>
  </ol>

<% end %>

app/views/users/edit.html.erb
<% page_title t("settings") %>

<%= render 'form' %>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
  <li>
    <%= link_to user.username, user_path(user.username) %>
    <% if (current_user && current_user.admin?) %>
    / <%= link_to "delete", user_path(user.username), :class => "delete", :method => :delete, :confirm => "Are you sure?" %>
    <% end %>
  </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% page_title t("signup") %>

<%= render 'form' %>

app/views/users/show.html.erb
<% page_title @user.username %>
<% page_id "profile" %>

<% if signed_in? && (@user == current_user) %>
  <%= render 'swatches/form' %>
<% end %>  

<ul id="paintbox"></ul>

<% content_for :javascripts do %>
  <%= javascript_include_tag "profile" %>
<% end %>